### PR TITLE
Add Banner to readme

### PR DESCRIPTION
**Pull request by kolibril13**
see here:
https://github.com/ManimEditorProject/manim_editor/blob/67472a5b161b973aa04d3dc02874aaecf672da67/README.md

### CODE REVIEW

**Comment by christopher-besch** [comment]
Could the shapes be located behind the text on the right side, like with Manim itself?
Or does that look weird?
grafik

**Comment by christopher-besch** [comment]
And some rounded corners would be sweet, but It's already great the way it is.

**Comment by christopher-besch** [comment]
I've improved the alignment a bit:
[https://github.com/ManimEditorProject/manim_editor/blob/added-banner/README.md](https://github.com/ManimEditorProject/manim_editor/blob/added-banner/README.md)

**Comment by kolibril13** [comment]
image
that's another iteration

**Comment by christopher-besch** [comment]
Getting closer!

**Pull request merged**
